name: 'auto: Release Note Drafter'

on:
  push:
    branches: [main]
    paths:
      - apps/**
      - packages/**
      - Dockerfile
      - package.json
      - turbo.json

  workflow_dispatch: {}

concurrency:
  group: auto-release-notes-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: toolmantim/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}