name: 'Test Annotations in PostHog'

on:
  workflow_dispatch:
    inputs:
      content:
        description: 'Content to send as an annotation'
        required: true
        default: 'Test Annotation'

jobs:
  test:
    name: Test!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Test Annotations
        uses: ./
        with:
          project_id: '31744'
          api_key: ${{ secrets.POSTHOG_API_KEY }}
          content: ${{ inputs.content }}

      # You will need to go to PostHog instance to check, in future use GH-action or API to check output in automated fashion....
